t1 = 'a', 'b', 'c'
t2 = ('a', 'b', 'c')
t3 = ('d', 'e')
print(t1 == t2)
print('True')
print(t1 > t3)
print('True')
print(t1 < t3)
print('False')
print(t2 + t3)
print('"a", "b", "c", "d", "e"')
print([t2 + t3])
print("[('a', 'b', 'c', 'd', 'e')]")
print(t1)
print("'a','b','c'")